# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="anilrouthu5@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/spring-boot-docker-test-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} /var/lib/docker/tmp/

# Add the application's jar to the container
ADD ${JAR_FILE} spring-boot-docker-test.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/spring-boot-docker-test.jar"]

